#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/customerdb
#    username: root
#    password: 1234
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: none
#    show-sql: true

#token:
#  secret: ksajldhjkJAAH123JAKHDkldgksljhgslklsdkgfuekbj
#  expiration_time: 864000000

review-service:
  url: http://localhost:8060