spring:
  datasource:
    url: jdbc:mysql://10.2.0.4:8082/orderdb
    username: root
    password: password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081

restaurant:
  search:
    item:
      url: http://10.2.0.4:8080/item/id/